### ISSUE TITLE
Value Type in loadBalancerSenderServerWeight

### ISSUE THREAD

**Issue by larsweiler** [availo/wowza-vhost-loadbalancer#1]
In the README you describe to use the Type Integer for loadBalancerSenderServerWeight

``` xml
<Property>
    <Name>loadBalancerSenderServerWeight</Name>
    <Value>5</Value>
    <Type>Integer</Type>
</Property>
```

Actually this throws the Error
    ERROR server comment - LoadBalancerEdge.run: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String

By using <Type>String</Type> everything is working.

**Comment by brynjare** [comment]
Thank you for spotting the error, and for reporting it.

It took some time before I was able to look into this because of summer vacation, but the fix itself was pretty small - assuming I haven't introduced any new bugs or overlooked anything. I wasn't aware of the problem until now, but it turns out I had left out the <Type> property in my own configs.

You should be able to use the proper <Type>Integer</Type> now, but the fix allows for old configs as well. Thanks again!

**Comment by larsweiler** [comment]
Thanks a lot for resolving this minor problem! No worries for the delay.

Just installed the fixed version and it works fine with Type Integer set.

**Comment by pilgrims1** [comment]
Dear.... brynjare....
Can You Help me? please.....

I have 1 or 2 physical server machine with perpetual licence.

I already achieve that 10 more VHosts (binded it's own ip and NIC) works fine - 1 origin, others edge application and stream running successfully.

My goal is
thru your module....
Make load balancing with above VHosts in one physical server.

Is it possible?

If not.....

below is possible???
1 Load Balancer Listener on physical server with 1 or 2 origin Vhost.
so many Load Balancer Sender in VHosts(already binded it's own ip(NIC)) on 1 Physical Server.

My licence is WSE 4.0.5.

**Comment by brynjare** [comment]
Please create a separate issue for new questions. This issue was closed over a year ago, so it's not easy to tell when new comments are made on it.

As for loadbalancing locally on one physical server, that's not what this module is designed for. With the current design of it, it's not possible to run both the Sender (the loadbalancer) and the Listener (the edge servers that receive the connections) on the same Wowza setup.

This module is also looking specifically at the whole Wowza server's current resource usage, and not VHost-specific usage. In other words, all your vhosts on the same server will report the same numbers - and there will be no benefit by loadbalancing to a single server either.

In any case, you will need at _least_ two separate Wowza installations currently. (But I am guessing there should be a more suitable way to do what you wish to do, to be honest. This module is probably not what you are looking for with your current design.)
