### ISSUE TITLE
Supporting Wowza 4.x

### ISSUE THREAD

**Issue by loohaj** [availo/wowza-vhost-loadbalancer#3]
Hi,

I would like to know if you are planning to upgrade the wowza-vhost-loadbalancer solution to fit for Wowza 4? 
There is no httpstreamers.xml in Wowza 4, so we can not use your loadbalancer on our Wowza 4 based CDN platform.
If you have any solution to fix this, please share it with us.
Thanks a lot,
Csaba

**Comment by brynjare** [comment]
Hi Csaba,

Unfortunately, I haven't gotten around to upgrading my test servers to Wowza 4 yet - so for the time being, I don't know how much work it will be to add support for Wowza 4.x.

Due to other projects with deadlines this and next month, I am currently not sure when you can expect an update from me on this. Sorry about that!

If anyone else has looked into this, any comments or pull requests are very welcome.

**Comment by brynjare** [comment]
Just a small update here: HTTPStreamers.xml is apparently no longer a server-wide config file, but I managed to make the module work in Wowza Streaming Engine 4.0.3 when creating HTTPStreamers.xml (with the relevant changes) under the load balancer vhosts' config directories instead.

This could be a good thing, all in all, since it should be possible to run the load balancer sender(s) on Wowza servers that also can act as listener(s) - instead of wasting resources by keeping them separate. In order for this to be possible, however, the module needs to be able to map senders and receivers separately from the VHost names.

I'm working on an update for this at the moment, and will also remove a couple of other annoyances. The config syntax will change, but I expect the module itself to work with both Wowza Media Server 3.x and Wowza Streaming Engine 4.

**Comment by Freak416** [comment]
Hi brynjare,
are there any updates from your side regarding the Wowza 4 compatibility? Would be great to hear some news...

**Comment by brynjare** [comment]
Hi,

I've been running it successfully by extracting the file 'com/wowza/wms/conf/HTTPStreamers.xml' from wms-server.jar (under the lib/-folder), and copying it to every VHost config folder, and then creating the relevant changes.

Other than this file being packed in the jar file (and moving from the server config directory over to each respective vhost's config directory), I can't remember any other changes.

Due to priority changes, I was unable to continue preparing an updated version - but hopefully, you should be able to get it running on version 4 by following these two extra steps!

**Comment by brynjare** [comment]
Hi again,

Just a small update here - since I started looking into this again earlier this evening.

I'm going to see if I can commit the beta version of the next version before I leave on vacation in a couple of weeks. It seems to work fairly well here, and the main thing left to do now is probably to wrap it up in a new .jar, and to update the documentation to reflect the new changes.

Thanks for your patience (and for your interest!) in the meantime.

**Comment by pinkladywithcoco** [comment]
Hi Brynjare,
- Could you write step by step how to use this load-balancer with wowza streaming engin 4.x ?? please, becouse i need it, but dont know how to use it.

**Comment by brynjare** [comment]
Unfortunately, other than my lab testing of Wowza 4.x back in 2014, I haven't been working with Wowza at all these past two years. I was also told that Wowza's load balancer addon for version 4 is a lot more advanced than the older version, and offers the same type of features that I ended up implementing for 2.x and 3.x:

https://www.wowza.com/products/addons/dynamic-load-balancing-solution

Is there anything my (old) module offers that won't work with the official addon? If there is, I would strongly recommend looking into extending the new version instead.

**Comment by brynjare** [comment]
Closing this, as I no longer run Wowza.

Anyone interested in loadbalancing with Wowza 4.0 should check out Dynamic Load Balancing AddOn 4.0 before considering this module, since this one is based on the old and more limited LoadBalancer 2.0 module,
