### ISSUE TITLE
loadBalancerSenderRedirectAddress is ignored

### ISSUE THREAD

**Issue by kriborg** [availo/wowza-vhost-loadbalancer#4]
Hi

Here is our config server.xml config:

``` xml
<Property>
    <Name>loadBalancerSenderRedirectAddress</Name>
    <Value>192.168.1.50</Value>
</Property>

When checking the   Loadbalancer?ServerinfoXML the <redirect> is not updated.

<LoadBalancerServerInfo>
    <LoadBalancerServer>
        <weight>1</weight>
        <connectCount>1</connectCount>
        <outRate>4</outRate>
        <status>RUNNING</status>
        <inRate>4</inRate>
        <redirectCount>0</redirectCount>
        <lastMessage>632 milliseconds</lastMessage>
        <redirect>10.0.0.5</redirect>
        <debug>4.0</debug>
        <serverId>2901d472-3989-463b-95e0-24c0a1246f95</serverId>
    </LoadBalancerServer>
    <LoadBalancerServer>
        <weight>1</weight>
        <connectCount>3</connectCount>
        <outRate>10</outRate>
        <status>RUNNING</status>
        <inRate>1</inRate>
        <redirectCount>0</redirectCount>
        <lastMessage>620 milliseconds</lastMessage>
        <redirect>10.0.0.2</redirect>
        <debug>10.0</debug>
        <serverId>18d23b29-20e9-4427-a1cd-071fb2b14461</serverId>
    </LoadBalancerServer>
</LoadBalancerServerInfo>
```

**Comment by brynjare** [comment]
Hey!

I don't recommend setting loadBalancerSenderRedirectAddress in Server.xml at all, unless you need it for compatilibity reasons with other environments. (Step 4 at https://github.com/availo/wowza-vhost-loadbalancer#step-4-optional and step 5, right below.)

The setting should go in each VHost.xml file instead, since that's the only way to get a unique address per VHost. My loadbalancer version is probably trying to be too clever, and not realising that in some environments, the Server.xml setting is all you need - and will therefore ignore it even though it should be considered.

Let me know if it still doesn't work as intended if you move the setting to VHost.xml!
